services:
  - type: web
    name: hand-tracking-api
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn index:app
    envVars:
      - key: PORT
        value: 5000
