services:
  - type: web
    name: apiPortfolio
    runtime: node
    region: oregon
    plan: free
    buildCommand: "npm install"
    startCommand: "node index.js"
    envVars:
      - key: PORT
        value: 5000
      - key: PYTHON_API_URL
        value: "https://pythonopencvserve.onrender.com"
